@echo off
echo Starting CCTV AI Security System...

echo Starting Backend API...
start cmd /k "cd backend && python -m uvicorn main:app --reload"

echo Starting AI Camera Pipeline...
start cmd /k "cd ai_pipeline && python -m uvicorn main:app --port 8001"

echo Starting React Dashboard...
start cmd /k "cd frontend && npm run dev"

echo All services started!
echo Please wait a few seconds for the camera to initialize...
timeout /t 5

echo Opening Dashboard in browser...
start http://localhost:5050/
