@echo off
echo Starting CCTV AI Security System...

echo Starting Backend API...
start "Backend" cmd /k "cd /d "%~dp0backend" && "..\.venv\Scripts\python.exe" -m uvicorn main:app --reload"

echo Starting AI Camera Pipeline...
start "AI Pipeline" cmd /k "cd /d "%~dp0ai_pipeline" && "..\.venv\Scripts\python.exe" -m uvicorn main:app --port 8002"

echo Starting React Dashboard...
start "Frontend" cmd /k "cd /d "%~dp0frontend" && npm run dev"

echo All services started!
echo Please wait a few seconds for the camera to initialize...
timeout /t 5

echo Opening Dashboard in browser...
start http://localhost:5050/
